Repo.WebUI/Controllers/CityController.cs
using Repo.Contracts.Repositories;
using Repo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Repo.WebUI.Controllers
{
    public class CityController : Controller
    {
        internal IRepositoryBase<State> state;
        internal IRepositoryBase<Country> country;
        internal IRepositoryBase<City> city;
        public CityController(IRepositoryBase<State> state, IRepositoryBase<Country> country, IRepositoryBase<City> city)
        {
            this.state = state;
            this.country = country;
            this.city = city;
        }
        // GET: City
        public ActionResult Index()
        {
            return View(city.getALL());
        }
        public ActionResult Create()
        {
            ViewBag.StateList = new SelectList(state.getALL(), "Id", "Name");
            return View();
        }
        [HttpPost]
        public ActionResult Create(City city)
        {
            this.city.Insert(city);
            this.city.Commit();
            return RedirectToAction("Index");
        }
    }
}

Repo.WebUI/Controllers/CountryController.cs
using Repo.Contracts.Repositories;
using Repo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Repo.WebUI.Controllers
{
    public class CountryController : Controller
    {
        internal IRepositoryBase<Country> country;

        public CountryController(IRepositoryBase<Country> country)
        {
            this.country = country;
        }
        // GET: Country
        public ActionResult Index()
        {
            return View(country.getALL());
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Country country)
        {
            this.country.Insert(country);
            this.country.Commit();
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int? id)
        {
            return View(country.getSingle(id));
        }
        [HttpPost]
        public ActionResult Edit(Country country)
        {
            this.country.Update(country);
            this.country.Commit();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int? id)
        {
            return View(country.getSingle(id));
        }

        public ActionResult Delete(int? id)
        {
            return View(country.getSingle(id));
        }
        [HttpPost]
        public ActionResult Delete(Country country)
        {
            this.country.Delete(country);
            this.country.Commit();
            return RedirectToAction("Index");
        }
    }
}

Repo.WebUI/Controllers/StateController.cs
using Repo.Contracts.Repositories;
using Repo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Repo.WebUI.Controllers
{
    public class StateController : Controller
    {
        internal IRepositoryBase<State> state;
        internal IRepositoryBase<Country> country;

        public StateController(IRepositoryBase<State> state,IRepositoryBase<Country> country)
        {
            this.state = state;
            this.country = country;
        }
        // GET: state
        public ActionResult Index()
        {
            return View(state.getALL());
        }

        public ActionResult Create()
        {
            ViewBag.CountryList = new SelectList(country.getALL(),"Id","Name");
            return View();
        }
        [HttpPost]
        public ActionResult Create(State state)
        {
            this.state.Insert(state);
            this.state.Commit();

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int? id)
        {
            ViewBag.CountryList = new SelectList(country.getALL(), "Id", "Name");
            return View(state.getSingle(id));
        }
        [HttpPost]
        public ActionResult Edit(State state)
        {
            this.state.Update(state);
            this.state.Commit();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int? id)
        {
            return View(state.getSingle(id));
        }

        public ActionResult Delete(int? id)
        {
            return View(state.getSingle(id));
        }
        [HttpPost]
        public ActionResult Delete(State state)
        {
            this.state.Delete(state);
            this.state.Commit();
            return RedirectToAction("Index");
        }
    }
}

Repo.WebUI/Views/City/Create.cshtml
@model Repo.Models.City
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{

    @Html.LabelFor(m => m.Name)
    @Html.EditorFor(m => m.Name)
    <br />
    @Html.LabelFor(m => m.State_Id)
    @Html.DropDownListFor(m => m.State_Id, ViewBag.StateList as SelectList)
    <br />
    <input type="submit" value="Submit" />
}

Repo.WebUI/Views/City/Index.cshtml
@model IEnumerable<Repo.Models.City>
@{
    ViewBag.Title = "Index";
}
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tbl_State.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tbl_State.tbl_Country.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tbl_State.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tbl_State.tbl_Country.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

Repo.WebUI/Views/Country/Create.cshtml
@model Repo.Models.Country
@{
    ViewBag.Title = "Create";
}

<div class="container">
    <div class="row header">
        <h1>Country</h1>
        <h3>Create a country</h3>
    </div>
    <div class="row body">
        @using (Html.BeginForm("Create", "Country", FormMethod.Post))
        {
            <div class="ui grid center aligned">
                <div class="two wide column">@Html.LabelFor(m => m.Name, "Country")</div>
                <div class="twelve wide column">@Html.TextBoxFor(m => m.Name)</div>
            </div>
            <div class="ui grid left aligned">
                <input type="submit" class="ui fluid large brown inverted button" value="Submit" />
            </div>
        }
    </div>
</div>

Repo.WebUI/Views/Country/Delete.cshtml
@model Repo.Models.Country
@{
    ViewBag.Title = "Delete";
}

<div class="container">
    <div class="row header">
        <h1>Country</h1>
        <h3>Country details</h3>
    </div>
    <div class="row body">

        @using (Html.BeginForm())
            {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            <div class="ui grid center aligned">
                <div class="two wide column">@Html.DisplayNameFor(model => model.Name)</div>
                <div class="twelve wide column">@Html.DisplayFor(model => model.Name)</div>
            </div>
            <div class="ui grid left aligned">
                @Html.ActionLink("Back to List", "Index", null, new { @class = "ui fluid large brown inverted button" })
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <input type="submit" value="Delete" class="ui fluid large inverted brown button" />
                }
            </div>
        }
    </div>
</div>

Repo.WebUI/Views/Country/Details.cshtml
@model Repo.Models.Country
@{
    ViewBag.Title = "Details";
}

<div class="container">
    <div class="row header">
        <h1>Country</h1>
        <h3>Country details</h3>
    </div>
    <div class="row body">

        @using (Html.BeginForm())
            {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            <div class="ui grid center aligned">
                <div class="two wide column">@Html.DisplayNameFor(model => model.Name)</div>
                <div class="twelve wide column">@Html.DisplayFor(model => model.Name)</div>
            </div>
            <div class="ui grid left aligned">
                @Html.ActionLink("Back to List", "Index", null, new { @class = "ui fluid large brown inverted button" })@Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "ui fluid large inverted brown button" })
            </div>
        }
    </div>
</div>

Repo.WebUI/Views/Country/Edit.cshtml
@model Repo.Models.Country
@{
    ViewBag.Title = "Edit";
}

<div class="container">
    <div class="row header">
        <h1>Country</h1>
        <h3>Create a country</h3>
    </div>
    <div class="row body">
                
        @using (Html.BeginForm())
            {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            <div class="ui grid center aligned">
                <div class="two wide column">@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })</div>
                <div class="twelve wide column">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="ui grid left aligned">
                @Html.ActionLink("Back to List", "Index", null, new { @class= "ui fluid large brown inverted button" })<input type="submit" class="ui fluid large brown inverted button" value="Submit" />
            </div>
        }
    </div>
</div>

Repo.WebUI/Views/Country/Index.cshtml
@model IEnumerable<Repo.Models.Country>
@{
    ViewBag.Title = "Index";
}
<div class="container">
    <div class="row header">
        <h1>Country</h1>
        <h3>List of countries in database</h3>
    </div>
    <div class="row body">
        @foreach (var item in Model)
        {
            <div class="ui grid center aligned">
                <div class="two wide column">@Html.DisplayFor(modelItem => item.Name)</div>
                <div class="twelve wide column">
                @Html.ActionLink("Edit", "Edit", new { id = item.Id },new { @class = "ui green button"})
                @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "ui orange button" })
                @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "ui red button" })</div>
            </div>
        }
        <div class="ui grid left aligned">
            @Html.ActionLink("Create New", "Create", null, new { @class = "ui fluid large brown inverted button" })
        </div>
    </div>
</div>

Repo.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/semantic.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/semantic.js"></script>
</head>
<body>

        @RenderBody()
</body>
</html>

Repo.WebUI/Views/State/Create.cshtml
@model Repo.Models.State
@{
    ViewBag.Title = "Create";
}

<div class="container">
    <div class="row header">
        <h1>State</h1>
        <h3>Create a state</h3>
    </div>
    <div class="row body">
        @using (Html.BeginForm("Create", "State", FormMethod.Post))
        {
            <div class="ui grid center aligned">
                <div class="two wide column">@Html.LabelFor(m => m.Name, "State")</div>
                <div class="twelve wide column">@Html.TextBoxFor(m => m.Name)</div>
            </div>
            <div class="ui grid center aligned">
                <div class="two wide column">@Html.LabelFor(m => m.Country_Id, "Country")</div>
                <div class="twelve wide column">@Html.DropDownListFor(m => m.Country_Id, ViewBag.CountryList as SelectList,new { @class= "ui search dropdown" })</div>
            </div>
            <div class="ui grid left aligned">
                <input type="submit" class="ui fluid large brown inverted button" value="Submit" />
            </div>
        }
    </div>
</div>

Repo.WebUI/Views/State/Delete.cshtml
@model Repo.Models.State
@{
    ViewBag.Title = "Delete";
}

<div class="container">
    <div class="row header">
        <h1>State</h1>
        <h3>State details</h3>
    </div>
    <div class="row body">

        @using (Html.BeginForm())
            {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            <div class="ui grid center aligned">
                <div class="two wide column">@Html.DisplayNameFor(model => model.Name)</div>
                <div class="twelve wide column">@Html.DisplayFor(model => model.Name)</div>
            </div>
            <div class="ui grid center aligned">
                <div class="two wide column">@Html.DisplayNameFor(model => model.tbl_Country.Name)</div>
                <div class="twelve wide column">@Html.DisplayFor(model => model.tbl_Country.Name)</div>
            </div>
            <div class="ui grid left aligned">
                @Html.ActionLink("Back to List", "Index", null, new { @class = "ui fluid large brown inverted button" })
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <input type="submit" value="Delete" class="ui fluid large inverted brown button" />
                }
            </div>
        }
    </div>
</div>

Repo.WebUI/Views/State/Details.cshtml
@model Repo.Models.State
@{
    ViewBag.Title = "Details";
}

<div class="container">
    <div class="row header">
        <h1>State</h1>
        <h3>State details</h3>
    </div>
    <div class="row body">

        @using (Html.BeginForm())
            {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            <div class="ui grid center aligned">
                <div class="two wide column">@Html.DisplayNameFor(model => model.Name)</div>
                <div class="twelve wide column">@Html.DisplayFor(model => model.Name)</div>
            </div>
            <div class="ui grid center aligned">
                <div class="two wide column">@Html.DisplayNameFor(model => model.tbl_Country.Name)</div>
                <div class="twelve wide column">@Html.DisplayFor(model => model.tbl_Country.Name)</div>
            </div>
            <div class="ui grid left aligned">
                @Html.ActionLink("Back to List", "Index", null, new { @class = "ui fluid large brown inverted button" })@Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "ui fluid large inverted brown button" })
            </div>
        }
    </div>
</div>

Repo.WebUI/Views/State/Edit.cshtml
@model Repo.Models.State
@{
    ViewBag.Title = "Edit";
}

<div class="container">
    <div class="row header">
        <h1>State</h1>
        <h3>Edit a state</h3>
    </div>
    <div class="row body">

        @using (Html.BeginForm())
            {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            <div class="ui grid center aligned">
                <div class="two wide column">@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })</div>
                <div class="twelve wide column">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="ui grid center aligned">
                <div class="two wide column">@Html.LabelFor(model => model.Country_Id, htmlAttributes: new { @class = "control-label col-md-2" })</div>
                <div class="twelve wide column">
                    @Html.DropDownListFor(model => model.Country_Id, ViewBag.CountryList as SelectList, new { @class = "ui search dropdown" } )
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="ui grid left aligned">
                @Html.ActionLink("Back to List", "Index", null, new { @class = "ui fluid large brown inverted button" })<input type="submit" class="ui fluid large brown inverted button" value="Submit" />
            </div>
        }
    </div>
</div>

Repo.WebUI/Views/State/Index.cshtml
@model IEnumerable<Repo.Models.State>
@{
    ViewBag.Title = "Index";
}

<div class="container">
    <div class="row header">
        <h1>State</h1>
        <h3>List of states in database</h3>
    </div>
    <div class="row body">
        @foreach (var item in Model)
        {
            <div class="ui grid center aligned">
                <div class="two wide column">@Html.DisplayFor(modelItem => item.Name)</div>
                <div class="three wide column">@Html.DisplayFor(modelItem => item.tbl_Country.Name)</div>
                <div class="ten wide column">
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "ui green small button" })
                    @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "ui orange small button" })
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "ui red small button" })
                </div>
            </div>
        }
        <div class="ui grid left aligned">
            @Html.ActionLink("Create New", "Create", null, new { @class = "ui fluid large brown inverted button" })
        </div>
    </div>
</div>